### PR TITLE
Blade if's

### PR DESCRIPTION
**Pull request by m1guelpf**
This pull request adds support for Blade's native conditionals.

### CODE REVIEW

**Comment by gizburdt** [comment]
Will discuss this with the team. This will break Laravel 5.4 compatibility

**Comment by m1guelpf** [comment]
@gizburdt Updates?

**Comment by gizburdt** [comment]
We'ere not merging this, because it breaks backwards compatability. We will keep it open for the future. We're going to tag all repo's with for 5.4 and 5.5. This can be merged in the 5.5 tag

**Comment by gizburdt** [comment]
We are going to tag a new version, can you please fix the merge conflicts? Then we will merge this PR :)

**Comment by gizburdt** [comment]
@m1guelpf Updates? :)

**Comment by m1guelpf** [comment]
@gizburdt I'll try to fix merge conflicts today.

**Pull request closed without merging**
