### PR TITLE
Readme notice for view:clear

### PR DESCRIPTION
**Pull request by danrichards**

### CODE REVIEW

**Comment by ovanschie** [comment]
I don't see why this is necessary?

**Comment by gizburdt** [comment]
Sorry, me neither

**Comment by danrichards** [comment]
Hmm, maybe it was just something I did. I had to clear the view cache after composer updating with new directives.

**Comment by gizburdt** [comment]
Yeah, that's sometimes the case after updating plugins. But I think it's not necessary to add it to our plugin/docs. Thanks for the help though! :)

**Comment by danrichards** [comment]
The issue was I used a new directive that did not exist yet, brought in the updated package with composer, views were already compiled, refreshed and nothing.

Granted, I was trying to use a directive that I hadn't pulled in. So it makes sense that it didn't work, but it's not to say someone else could not make the same misstep.

**Pull request closed without merging**
