### PR TITLE
Add support for laravel 8

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by gizburdt** [comment]
Can you add ^8.0 to travis.yml so it will be tested against this Laravel version? :)

**Comment by lloricode** [comment]
@gizburdt done!

**Comment by gizburdt** [comment]
Thanks! Will rerun tests and tag when 8.0 is released :)

**Comment by ppx17** [comment]
[8.0 is released](https://laravel-news.com/laravel8)! :innocent:

**Comment by gizburdt** [comment]
Can someone please have a look at the failing tests? :)

**Comment by lloricode** [comment]
> Can someone please have a look at the failing tests? :)

maybe rerun the test, since this PR created, the orchestra/testbench v6 is  not release yet
this PR made for preparation

**Pull request merged**
